title: Nina Hosseini-Kivanani
description: Personal website showcasing research in NLP, Computer Vision, and Multilingual Speech Recognition
author: Nina Hosseini-Kivanani
email: hkivanani@gmail.com
baseurl: "/NinaKivanani"
url: "https://ninahkivanani.github.io"

# GitHub Pages configuration
theme: jekyll-theme-minimal
